Feat ot112 17 create user model controller migration
alkemyTech/OT112-Server pull request #1
Opened 2021-11-24 17:48 UTC by AleYanc

Created the User model, controller with CRUD actions, implemented soft delete and added roleId column (Waiting for the roles table to be created to work on the associations) and routes.

Extras: 
-Added pagination to users index with limit and offset
-Using representers to serialize user or users object, waiting for the team to select a serializer gem.

2021-11-24 22:27 UTC, FernandoCiballero commented on Gemfile
> +gem 'bcrypt'
No sería conveniente agregar `bcrypt` en este ticket ya que no se pide autenticación.

2021-11-24 22:28 UTC, FernandoCiballero commented on Gemfile
> +gem 'acts_as_paranoid'
está muy bien para resolver el soft delete :+1:

2021-11-24 22:30 UTC, FernandoCiballero commented on app/controllers/api/v1/users_controller.rb
> +    end
Debería estár solamente el controlador vacio ya que el ticket no especifica ningún endpoint :eyes:

2021-11-24 22:33 UTC, FernandoCiballero commented on app/representers/user_representer.rb
> +end
Este achivo tambien debería ser eliminado, ya que en este commit no debería haber endpoint para serializar.

2021-11-24 22:34 UTC, FernandoCiballero commented on app/representers/users_representer.rb
> +end
Idem anterior. :arrow_up:

2021-11-24 22:38 UTC, FernandoCiballero commented on config/database.yml
>    # To create additional roles in postgres see `$ createuser --help`.
Deberias eliminar esa linea y en todo caso la agregamos en otro commit como un fix.

2021-11-24 22:40 UTC, FernandoCiballero commented on config/routes.rb
> +      resources :users
Sería conveniente quitar resources y agregarlo cuando el ticket pida crear un endpoint.

2021-11-24 22:46 UTC, FernandoCiballero commented on db/migrate/20211124022558_drop_users_table.rb
> +end
Para evitar confusiones a futuro deberías eliminar este archivo, ya que se puede tornar confuso para seguir el historial de migraciones y se tendrias mucho código `useless`. Es mejor usar el `drop` cuando específicamente se requiera eliminar la tabla(aunque es muy raro que se elimine una tabla en un proyecto real).

2021-11-24 22:56 UTC, FernandoCiballero commented on db/migrate/20211124022637_create_users.rb
> +      t.string :password_digest, :null => false
Sería conveniente remplaza `:null => false` por `null: false`, ya que esta última es la notación recomendada actualmente.

2021-11-24 22:58 UTC, FernandoCiballero commented on db/migrate/20211124022637_create_users.rb
> +    end
sería conveniente indexar el campo `email` se esta manera:
`add_index :users, :email, unique: true`

2021-11-24 23:06 UTC, FernandoCiballero commented on db/seeds.rb
> +User.create(first_name:'Test5',last_name:'User5',email:'test@user5.com',password:'123456')
Deberías elminar estos seeds ya que no se piden en el ticket(en todo caso se podrían agregar a futuro)

2021-11-24 23:22 UTC, FernandoCiballero commented on app/models/user.rb
> +  validates :last_name, presence: true, uniqueness: true
En este caso el campo `first_name` y `last_name` debería admitir valores repetidos (se debería eliminar `uniqueness: true`).

2021-11-24 23:23 UTC, FernandoCiballero commented on app/models/user.rb
>    has_secure_password
Se debería eliminar esta linea ya que no se corresponde con el ticket.

2021-11-25 02:12 UTC, FernandoCiballero commented on app/controllers/api/v1/users_controller.rb
> +end
Solo un detalle, si ves ese signo menos en rojo es porque github pide que agregues una linea vacia al final del archivo.

2021-11-25 02:13 UTC, AleYanc commented on app/controllers/api/v1/users_controller.rb
> +end
Cómo sería eso? Le doy Enter y hago una línea más después del end?

2021-11-25 02:14 UTC, FernandoCiballero requested changes
Quedaron unos cambios por revisar para que esté listo el ticket.

2021-11-25 22:02 UTC, FernandoCiballero commented on app/controllers/api/v1/users_controller.rb
> +end
Si, un enter en el end

2021-11-25 22:04 UTC, FernandoCiballero reviewed
.

2021-11-26 03:18 UTC, merged