Feat ot112 32 end point eliminar usuario
alkemyTech/OT112-Server pull request #28
Opened 2021-11-30 23:21 UTC by Darkzho

Tengo dudas con el método destroy ¿sólo va así o hay que agregar algo más? 

EL ticket decía que había que agregar borrado lógico, por eso agregue el restore ¿Era necesario? pregunto ya que el usuario ya tenía la opción de deleted_at

2021-11-30 23:47 UTC, FernandoCiballero commented on app/controllers/api/v1/users_controller.rb
> +  end
Podrias modificarlo así para que quede un poco más completo:
```
def destroy
        if @user.destroy
          head :no_content
        else
          render json: @user.errors.messages , status: 422
        end
      end
```

2021-11-30 23:49 UTC, FernandoCiballero requested changes
Buenísimo!!!!
Quedaría eliminar el `restore` ya que por ahora no lo pide el ticket.

2021-12-02 01:56 UTC, JeremasPosta approved these changes

2021-12-08 17:52 UTC, JeremasPosta commented
Este branch sigue vigente o fue reemplazado por https://github.com/alkemyTech/OT112-Server/pull/45 ?

2021-12-10 03:40 UTC, closed without merging