OT112-42: Create categories endpoint
alkemyTech/OT112-Server pull request #31
Opened 2021-12-01 03:21 UTC by zFranco1

Added create endpoint into categories controller.
Categories serializer was added as a suggestion from mentor.
Also added routes for categories.

2021-12-01 03:36 UTC, JeremasPosta commented
Te parece subir casa archivo en un commit individual para mantener el formato que venimos usando?

2021-12-01 03:40 UTC, JeremasPosta commented on config/routes.rb
> +      resources :categories
Por qué usar un resource si sólo se pide un post en el ticket?

2021-12-01 16:24 UTC, zFranco1 commented on config/routes.rb
> +      resources :categories
Si, tenés razón. Lo tengo medio de reflejo ponerlo cuando comienzo con algunas implementaciones.
Con respecto a subir un commit individual por archivo, de hecho lo venía haciendo. Lo que sucede es que hice rebase antes de crear el pull request y no bien después de las correcciones.

2021-12-01 21:07 UTC, AleYanc approved these changes

2021-12-02 02:19 UTC, JeremasPosta approved these changes

2021-12-02 02:20 UTC, JeremasPosta commented
Me parece a mi o desaparecio el `routes.rb` del PR?

2021-12-02 03:04 UTC, zFranco1 commented
> Me parece a mi o desaparecio el routes.rb del PR?

Luego de tus comentarios, y de actualizar el branch  para que quede un commit por archivo, me pareció que quizás no era fundamental para este ticket en particular dejar esa modificación para ese archivo, aunque así como lo había puesto de igual manera se iba a utilizar para los tickets siguientes (entiendo que hay que crear más endpoints para ese controlador). Por otro lado, crear un resource singular para este endpoint solo no tiene sentido si luego se agregan otros más. 

De cualquier manera aguardo comentarios ya que es una modificación de una sola línea y me gustaría saber que es lo que creen más conveniente.

2021-12-02 12:53 UTC, gervic08 commented on app/controllers/api/v1/categories_controller.rb
> +    if params[:name] && params[:name].is_a?(String)
(String) podría escribirse sin (), por convención

2021-12-02 12:53 UTC, gervic08 approved these changes

2021-12-02 13:49 UTC, FernandoCiballero commented on app/controllers/api/v1/categories_controller.rb
> +    if params[:name] && params[:name].is_a?(String)
Tendrias que ver de validar bien que no sea string, y lanzar un excepcion en caso de no serlo. Tene en cuenta que los params son de tipo string.

2021-12-02 13:50 UTC, FernandoCiballero requested changes
Faltaría agregar la ruta correspondiente a este endpoint.

2021-12-03 02:41 UTC, FernandoCiballero requested changes
.

2021-12-03 02:41 UTC, FernandoCiballero commented on app/controllers/api/v1/categories_controller.rb
> +    if params[:name] && params[:name].is_a?(String)
En este caso la validación sería:
```
params[:name].to_i.class != Integer
```

2021-12-03 04:10 UTC, zFranco1 commented
Fernando, vas a tener que revisar la validación en cuestión. Estuve probando de la forma que recomendaste entre otras que estuve investigando y no me funcionó bien.

2021-12-03 22:05 UTC, FernandoCiballero commented on app/controllers/api/v1/categories_controller.rb
> +    # end
Deberías borrar esto que está comentado ya que ensucia un poco el código.

2021-12-03 22:06 UTC, FernandoCiballero requested changes
Una pequeña modificación que quedó pendiente.

2021-12-04 00:21 UTC, zFranco1 commented
Se hicieron las modificaciones solicitadas. Debería controlarse pero parecería estar solucionada la validación.

2021-12-06 01:22 UTC, merged