Feat ott112 40 endpoint listado de categorias
alkemyTech/OT112-Server pull request #33
Opened 2021-12-01 15:19 UTC by gervic08

- Add index method to Categories controller
- Category Serializer created
- Add route to index method in categories controller

2021-12-02 14:27 UTC, FernandoCiballero commented on app/models/category.rb
> -  acts_as_paranoid
Segun tengo yo el modelo Category tiene soft delete. Fijate de hacer rebase periodicamente de los cambios en master.

2021-12-02 14:29 UTC, FernandoCiballero requested changes
Faltaría verificar lo de soft delete. Verifica siempre de estar actualizado con `master`.

2021-12-02 14:33 UTC, gervic08 commented on app/models/category.rb
> -  acts_as_paranoid
Ok, Fernando. La tabla no tiene la columna deleted_at, asi que en el caso de implementar soft delete habria que agregarla

2021-12-03 03:52 UTC, FernandoCiballero commented on app/controllers/api/v1/categories_controller.rb
> +    def index
Faltaría agregar el authorize request y validar si es administrador.

2021-12-06 02:45 UTC, merged