Feat ot112 56 slides index endpoint
alkemyTech/OT112-Server pull request #46
Opened 2021-12-07 16:57 UTC by AleYanc

Added slides controller with index action and a **slides** serializer that returns only the order and image, as the ticket requested, with admin verification also.

2021-12-07 17:20 UTC, gervic08 approved these changes

2021-12-07 23:08 UTC, JeremasPosta commented
Me parece que subiste un para de cambios que no corresponden, digamos, esos cambios en el modelo `User` corresponderian al ticket que lo modifico, no a este. O estoy errado?

2021-12-07 23:21 UTC, AleYanc commented
> Me parece que subiste un para de cambios que no corresponden, digamos, esos cambios en el modelo `User` corresponderian al ticket que lo modifico, no a este. O estoy errado?

Si hay un par de cambios que la verdad no sé por que me pidio que haga un add y commit, despues de hacer el db:migrate me tiró cambios en archivos que seguian exactamente igual que antes y yo no toqué, por si acaso les hice un commit y hoy en la daily iba a preguntar si los dropeo o los dejo, pero la verdad ni idea porque me pidió eso siendo que yo no les hice ningun cambio

2021-12-07 23:25 UTC, JeremasPosta commented
No, pasa que tu modelo `User` cambio respecto a tu local. Al cambiar y migrarlo, la gema de `Annotation` te actualizo las notas (son los cambios que subiste). Esos cambios deberian ya estar mergeados en master cuando actualizaron el modelo y agregaron esa migracion que vos corriste para `User`. Si no estan, deberian agregarlo en el ticket que corresponda. No aca. Igual lo vemos en  la daily de ultima.

2021-12-07 23:30 UTC, AleYanc commented
> No, pasa que tu modelo `User` cambio respecto a tu local. Al cambiar y migrarlo, la gema de `Annotation` te actualizo las notas (son los cambios que subiste). Esos cambios deberian ya estar mergeados en master cuando actualizaron el modelo y agregaron esa migracion que vos corriste para `User`. Si no estan, deberian agregarlo en el ticket que corresponda. No aca. Igual lo vemos en la daily de ultima.

Si tal cual, eso me estuve fijando, yo la master la tengo actualizada asi que algun problema con eso dudo que sea

2021-12-08 02:55 UTC, FernandoCiballero requested changes
Estaría bien el ticket con respecto Slide, no me que claro el por qué de las modificaciones en el modelo User.

2021-12-08 03:00 UTC, AleYanc commented
@FernandoCiballero yo tampoco tengo claro por qué se hicieron esos cambios, pero por lo que dijo Jeremías puede ser por la gema annotation, pero yo no toque nada, les hice un commit por si acaso

2021-12-10 05:16 UTC, merged