feat-OT112-53: add seeders Acitivity to db/seeds.
alkemyTech/OT112-Server pull request #50
Opened 2021-12-07 22:57 UTC by JorgeGarciaMdz

2021-12-08 00:15 UTC, JeremasPosta commented on db/seeds.rb
> +end
Le faltaría la línea en blanco al final del archivo.

2021-12-08 00:27 UTC, JeremasPosta approved these changes
Probado en local, funciona joya!

2021-12-08 02:58 UTC, FernandoCiballero commented on db/seeds.rb
> +  # ["name", "conent"]
Sería conveniente eliminar todo código comentado ya que la idea de Ruby es que el mismo código sea descriptivo de lo que se esta realizando.

2021-12-08 03:00 UTC, FernandoCiballero requested changes
Muy bien estructurado el seed :+1: , te deje un par de cosas para revisar.

2021-12-08 21:57 UTC, JorgeGarciaMdz commented on db/seeds.rb
> +  # ["name", "conent"]
dale fernando, voy a estar borrando los comentarios y realizando el seed con datos obtenidos del pdf.

2021-12-10 05:35 UTC, FernandoCiballero reviewed
Exelente Jorge!!! :+1:

2021-12-10 05:35 UTC, merged