Feat ot112 58 endpoint creacion slides
alkemyTech/OT112-Server pull request #54
Opened 2021-12-08 16:39 UTC by gervic08

- Add create method to slides controller. 
  * Admin user check
  * Base 64 image attached
  * Default value for "order" param set in -1 if it's not explicited
  
- Create route to create method

- Add support for base 64 in Application Record; Slide Model inherits from

- Add gem 'active_storage_base64'  - [(https://github.com/rootstrap/active-storage-base64)]

2021-12-08 16:53 UTC, AleYanc approved these changes

2021-12-08 16:53 UTC, AleYanc commented on app/controllers/api/v1/slides_controller.rb
> +    if admin?(@current_user)
Copada esta estructura para validar que sea admin! Estaba buscando justo una solución de este estilo para validar unos endpoints que tocaron en mis tickets

2021-12-08 16:57 UTC, gervic08 commented on app/controllers/api/v1/slides_controller.rb
> +    if admin?(@current_user)
Genial, Ale! aproveché que en application controller está creada esa función para utilizarla en todos los endpoints de los controladores que requieren ser admin para ejecutar la acción

2021-12-08 16:59 UTC, AleYanc commented on app/controllers/api/v1/slides_controller.rb
> +    if admin?(@current_user)
Sisi, esa la cree en un ticket previo, pero yo la estaba usando por ejemplo "admin?(@current_user) && @activity.update()" y estaba teniendo problemas para despues renderizar un json con los errores, pero con esa estructura que hiciste vos se soluciona joya, una masa

2021-12-08 17:58 UTC, JeremasPosta requested changes

2021-12-08 17:58 UTC, JeremasPosta commented on Gemfile
> +gem 'active_storage_base64'  # https://github.com/rootstrap/active-storage-base64
Hola Germán! Debería estar la gema agregada en orden alfabético, y creo que para seguir la línea el link debería ser a la web de RubyGems, no al repositorio.
De paso, le agregas la versión que requiere?

2021-12-08 17:58 UTC, JeremasPosta commented on config/routes.rb
>        get 'announcements', to: 'announcements#show'
Al aplicar Resources, no deberíamos sacar la linea 5 del método GET?

2021-12-08 20:14 UTC, gervic08 commented on Gemfile
> +gem 'active_storage_base64'  # https://github.com/rootstrap/active-storage-base64
Hola Jere, como va? dale, barbaro! hago esas modificaciones, me parece bien.

2021-12-08 20:16 UTC, gervic08 commented on config/routes.rb
>        get 'announcements', to: 'announcements#show'
No tengo idea xq se subieron esos cambios que no corresponden con mi ticket. Cuando arme el branch ya tenia el master actualizado

2021-12-10 04:25 UTC, FernandoCiballero commented on Gemfile
> +gem 'active_storage_base64'  # https://github.com/rootstrap/active-storage-base64
Quedó pendiente lo de ordenar alfabéticamente la gema.

2021-12-10 04:49 UTC, FernandoCiballero commented on app/controllers/api/v1/slides_controller.rb
> +      default = { order: order_array.max + 1 }
En esta línea estarías llamando al método `order_default` en lugar de la variable `order_array`

2021-12-10 04:54 UTC, FernandoCiballero commented on app/controllers/api/v1/slides_controller.rb
> +      order_array
Acá podés verificar que si la tabla de slides no tiene ningun registro se produce un error. Si `order_array` esta vacio, el método `max` retorna `nil`.

2021-12-10 12:15 UTC, gervic08 commented on app/controllers/api/v1/slides_controller.rb
> +      default = { order: order_array.max + 1 }
Si, Fernando, fue un error de tipeo, quise llamar a orden_default. Se me paso!

2021-12-10 12:19 UTC, gervic08 commented on app/controllers/api/v1/slides_controller.rb
> +      order_array
Dale, perfecto! yo no le hice tests aun. Lo subi para que veamos si cambiamos el metodo por alguno de active records, pero si utilizamos este, lo arreglo, lo testeo y lo vuelvo a subir! Finalmente, lo hago asociado a los slides de cada organizacion o así como está?

2021-12-13 04:24 UTC, merged