OT112-75: Seed added for Roles and Users.
alkemyTech/OT112-Server pull request #74
Opened 2021-12-17 02:20 UTC by JeremasPosta

Seeds added for both Roles and Users model. Required by:

https://alkemy-labs.atlassian.net/browse/OT112-75

2021-12-17 13:26 UTC, gervic08 commented
Muy bueno, Jere! Ordenado y claro

2021-12-17 13:26 UTC, gervic08 approved these changes

2021-12-19 23:49 UTC, FernandoCiballero commented on db/seeds.rb
> +users.each do |params|
Quedaria mejor usar `user` en lugar de `params`

2021-12-19 23:50 UTC, FernandoCiballero commented on db/seeds.rb
> +roles.each do |params|
Quedaria mejor usar `role` en lugar de `params`, solo para que sea mas natural de leer.

2021-12-19 23:52 UTC, FernandoCiballero requested changes
Muy bien el seed!!!  👍, faltaria editar un par de lineas y ya esta listo.

2021-12-19 23:53 UTC, JeremasPosta commented
OK OK! Ya lo soluciono. Gracias!

El dom., 19 de diciembre de 2021 20:53, Fernando Ciballero <
***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
>
> Muy bien el seed!!! 👍, faltaria editar un par de lineas y ya esta listo.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alkemyTech/OT112-Server/pull/74#pullrequestreview-835918577>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOP3X77XRE6N5DTHAAJSMV3URZV5ZANCNFSM5KHYO2RA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2021-12-20 00:09 UTC, JeremasPosta commented
@FernandoCiballero Listo!

2021-12-20 00:14 UTC, merged