fixed-slides-endpoints-messages
alkemyTech/OT112-Server pull request #81
Opened 2021-12-21 14:55 UTC by gervic08

- Fixed slides endpoints messages format

2021-12-21 23:05 UTC, JorgeGarciaMdz approved these changes
response ok.

2021-12-22 00:35 UTC, FernandoCiballero commented on app/controllers/api/v1/slides_controller.rb
> +  before_action :set_slide, only: [:show, :update, :destroy]
Es valido utilizar `%i` en un array de symbols:
```suggestion
  before_action :set_slide, only:  i%[show update destroy]
```

2021-12-22 00:35 UTC, FernandoCiballero commented on app/controllers/api/v1/slides_controller.rb
> +      render json: {msg: 'You are not authorized to perform that action'}, status: :unauthorized
Revisar el espaciado de las llaves en este archivo:
```suggestion
      render json: { msg: 'You are not authorized to perform that action' }, status: :unauthorized
```

2021-12-22 00:37 UTC, FernandoCiballero requested changes
Todo muy bien!!! quedaria revisar el espaciado de las llaves y ya estaria listo.

2021-12-27 00:32 UTC, merged